# Generated by Django 6.0 on 2025-12-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("institutions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="brand_color",
            field=models.CharField(
                default="#10b981",
                help_text="Hex code of the school's primary color",
                max_length=7,
            ),
        ),
    ]
