# Generated by Django 6.0 on 2025-12-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="acceptance_letter",
            field=models.FileField(
                blank=True, null=True, upload_to="acceptance_letters/"
            ),
        ),
    ]
